Citizen.CreateThread(function()
	AddTextEntryByHash(GetHashKey("hcbr17_exh_1"),"Tuning 01")
	AddTextEntryByHash(GetHashKey("hcbr17_exh_2"),"Tuning 02")
	AddTextEntryByHash(GetHashKey("hcbr17_exh_3"),"Tuning 03")
	AddTextEntryByHash(GetHashKey("hcbr17_part_1"),"Tuning 04")
	AddTextEntryByHash(GetHashKey("hcbr17_part_2"),"Tuning 05")
	AddTextEntryByHash(GetHashKey("hcbr17_part_3"),"Tuning 06")
	AddTextEntryByHash(GetHashKey("hcbr17_part_4"),"Tuning 07")
	AddTextEntryByHash(GetHashKey("hcbr17_seat_1"),"Tuning 08")
	AddTextEntryByHash(GetHashKey("hcbr17_seat_2"),"Tuning 09")
	AddTextEntryByHash(GetHashKey("hcbr17_tail_1"),"Tuning 10")
	AddTextEntryByHash(GetHashKey("hcbr17_winds_1"),"Tuning 11")
end)